language: cpp
git:
  depth: false
matrix:
  include:
  - os: linux
    dist: xenial
    services: docker
script: "docker build -f ./ubuntu-18.04.dockerfile ."
notifications:
  webhooks:
    secure: "RrPA9xykasI7grVQjodqDvhmUE7ZCjZdlYdeZALt7BCkJ3KHjTLAlP1KueQZS/hkysAtjYLcciLLNgV4mWkthJsUq3pwk5O3DlppWlil2N+v3l54Zf6Lb7Xb1aOvruHjqGcWY7KHaBSFzzFcP/PQibit1+znQ39gQcpzaDas8U+PWRzdpi+vwRtGuqT8e90CcsdU2QSqYuU9NJHkzm5CD+HdgoP73j6T5rQxCRrNQRD25Ut4mS9rS7mqz3KJbak87pdvKs4gzEmMkk+dSTTHu/pXVTF1W9+kC6FflPe6qAf5ZiYwpgZwiis+jARSOZmxiTbDAnpAfxNx6fawu+KVcgUclxurg50hxEl6UZn7Y4r87QWm4YdTUV31B0rAddsctfzmBK2htifkH0wysHYdDqNXzjktJcFy4emsTh5EHPz/iOH6sh5Jf3pirOd3lE79TUa9I1p0G5EgRsh3DgO4jVAa2+qvEL8EBmr+AJ9pvhNkCfKOCSSe0QhxgRNPuvePRkdb4B22igrlAbJBrBSZkwXar8lN+jUDDolKVd4dsNhqxo0DRQn8ofn+kbtNUG4hde5XrMcuA9WpWr0AlwQPZAAODXW+GuVUq0EaIwJNbX7S5uZpyEl8yfM40iBxN/4Ez27ffQLdfXHlggduPvUdAoasbEeyAeUnV7efqENAMqY="